# Generated by Django 6.0.1 on 2026-02-04 19:10

import django.utils.timezone
import downloads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. v2.0.0', max_length=128)),
                ('version_number', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('exe_file', models.FileField(upload_to=downloads.models.exe_upload_to)),
                ('file_size', models.CharField(blank=True, max_length=64, null=True)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_latest', models.BooleanField(default=False, help_text='Mark this release as the latest published build')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
