# Generated by Django 6.0.2 on 2026-02-07 16:46

import downloads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_activationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='code',
            field=models.CharField(default=downloads.models.generate_activation_code, max_length=100, unique=True),
        ),
    ]
