# Generated by Django 6.0.1 on 2026-02-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
    ]
