# Generated by Django 6.0.1 on 2026-02-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discord_ticket_channel_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
