# Generated by Django 6.0.2 on 2026-02-07 16:46

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_add_sellauth_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=shop.models.generate_order_id, max_length=50, unique=True),
        ),
    ]
