# Generated by Django 6.0.2 on 2026-02-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_order_order_id'),
        ('shop', '0015_product_images'),
    ]

    operations = [
    ]
